language: node_js
node_js:
  - "12"
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: source
